### ISSUE TITLE
why didn't the recipient receive the mail?

### ISSUE THREAD

**Issue by qinglong-kooboo** [peter-evans/sendgrid-action#2]
I followed the usage.
And the Github Action worked without error. 
![image](https://user-images.githubusercontent.com/40824476/75430203-f722d900-5985-11ea-8647-804b35807c98.png)

But the recipient didn't receive the mail, just nothing happened...
## This is my sendgrid.js
```
const sgMail = require('@sendgrid/mail');
console.log(sgMail)
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

const msg = {
    to: 'wu_thor@foxmail.com',
    from: 'wqlthor@163.com',
    subject: 'Hello world',
    text: 'Hello plain world!',
    html: '<p>Hello HTML world!</p>',
};

sgMail
    .send(msg)
    .then(() => console.log('Mail sent successfully'))
    .catch(error => console.error(error.toString()));
```

BTW, i didn't find it in the junk mail, and the recipient email address is valid and real.
Please help me..
[This is my repo](https://github.com/qinglong-kooboo/send-weather-email)

**Comment by peter-evans** [comment]
@qinglong-kooboo It looks correct to me so I have no idea why the recipient didn't receive it. Try sending to other email addresses, and maybe check your SendGrid account has sufficient quota.

**Comment by qinglong-kooboo** [comment]
Just to make sure i didn't make any mistake:
1.create a new account on SendGrid
2.create an SENDGRID_API_KEY on SendGrid
3.copy the key, paste to secrets.
anything i have missed?

**Comment by qinglong-kooboo** [comment]
> @qinglong-kooboo It looks correct to me so I have no idea why the recipient didn't receive it. Try sending to other email addresses, and maybe check your SendGrid account has sufficient quota.

May I ask which email provider you use? I think it might have something to do with the email provider..

**Comment by peter-evans** [comment]
[SendGrid](https://sendgrid.com/) is sending the emails. This action is not doing anything at all other than provide an environment where the SendGrid SDK is available to use. The SDK presumably sends an API call to SendGrid and then the email is sent from SendGrid to the recipient.

If you have issues receiving email I'm afraid there is not a lot I can do. Please check the SendGrid documentation and maybe contact SendGrid support if necessary.
